baseURL = "https://ring.nlnog.net/"
languageCode = "en-us"
title = "NLNOG RING"
publishDir = "HTML"

theme = "ring-anubis"
paginate = 10

disqusShortname = ""
googleAnalytics = ""


[author]
  name = "NLNOG RING"

[params]
   author = "NLNOG RING"
   customCSS = ["css/ring.css"]

[menu]

  [[menu.main]]
    name = "News"
    identifier = "news"
    url = "/news/"
    weight = 1

  [[menu.main]]
    identifier = "introduction"
    name = "Introduction"
    url = "/introduction/"
    weight = 2

  [[menu.main]]
    identifier = "participants"
    name = "Participants"
    url = "/participants/"
    weight = 3

  [[menu.main]]
    identifier = "security"
    name = "Security"
    url = "/security/"
    weight = 4

  [[menu.main]]
    identifier = "security"
    name = "Security"
    url = "/security/"
    weight = 4
  
  [[menu.main]]
    identifier = "user-guide"
    name = "User Guide"
    url = "/user-guide/"
    weight = 5

  [[menu.main]]
    identifier = "toolbox"
    name = "Toolbox"
    url = "/toolbox/"
    weight = 6

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 7

  [[menu.main]]
    identifier = "patrons"
    name = "Patrons"
    url = "/patrons/"
    weight = 8

  [[menu.user-guide]]
    identifier = "faq"
    name = "FAQ"
    url = "/user-guide/faq/"
    weight = 1

  [[menu.toolbox]]
    identifier = "looking-glass"
    name = "Looking Glass"
    url = "/toolbox/looking-glass/"
    weight = 1

  [[menu.toolbox]]
    identifier = "restful-api"
    name = "RESTful API"
    url = "/toolbox/restful-api/"
    weight = 2

  [[menu.toolbox]]
    identifier = "ring-sqa"
    name = "RING SQA"
    url = "/toolbox/ring-sqa/"
    weight = 3

  [[menu.toolbox]]
    identifier = "health-monitoring"
    name = "Health Monitoring"
    url = "/toolbox/health-monitoring/"
    weight = 4

  [[menu.contact]]
    identifier = "application-form"
    name = "Application Form"
    url = "/contact/application-form/"
    weight = 1


[taxonomies]
category = "categories"
tag = "tags"
series = "series"
